openapi: 3.0.0
info:
  title: Unifi API
  description: REST API for managing UDM Pro devices and networks.
  version: 1.0.0
servers:
  - description: UDM Pro API server
    url: '{scheme}://{host}:{port}'
    variables:
      scheme:
        enum:
          - http
          - https
        default: https
      host:
        default: localhost
      port:
        default: '8443'

paths:
  /api/auth/login:
    post:
      operationId: login
      tags:
      - auth
      summary: Authenticate user and return session cookie
      description: Login to Unifi console
      requestBody:
        description: Fields to authenticate with the console
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - username
              - password
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
        '403':
          description: Invalid Credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  level:
                    type: string
        
  
components:
  schemas:
    Authentication:
      title: AuthenticatedUser
      description: User properties
      type: object
      additionalProperties: false
      properties:
        unique_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        alias:
          type: string
        full_name:
          type: string
        email:
          type: string
        email_status:
          type: string
        email_is_null:
          type: boolean
        user_email:
          type: string
        phone:
          type: string
        avatar_relative_path:
          type: string
        avatar_rpath2:
          type: string
        status:
          type: string
        employee_number:
          type: string
        create_time:
          type: integer
        login_time:
          type: integer
        extras:
          $ref: '#/components/schemas/Extras'
        username:
          type: string
        local_account_exist:
          type: boolean
        password_revision:
          type: integer
        sso_account:
          type: string
        sso_uuid:
          type: string
        sso_username:
          type: string
        sso_picture:
          type: string
        uid_sso_id:
          type: string
        uid_sso_account:
          type: string
        uid_account_status:
          type: string
        groups:
          type: array
          items:
            $ref: '#/components/schemas/Group'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        permissions:
          $ref: '#/components/schemas/Permissions'
        scopes:
          type: array
          items:
            type: string
        cloud_access_granted:
          type: boolean
        only_local_account:
          type: boolean
        update_time:
          type: integer
        avatar:
          type: string
        nfc_token:
          type: string
        nfc_display_id:
          type: string
        nfc_card_type:
          type: string
        nfc_card_status:
          type: string
        role:
          type: string
        roleId:
          type: string
        id:
          type: string
        isOwner:
          type: boolean
        isSuperAdmin:
          type: boolean
        isMember:
          type: boolean
        maskedEmail:
          type: string
        accessMask:
          type: integer
        permissionMask:
          type: integer
        deviceToken:
          type: string
        ssoAuth:
          $ref: '#/components/schemas/Extras'
      required:
        - accessMask
        - alias
        - avatar
        - avatar_relative_path
        - avatar_rpath2
        - cloud_access_granted
        - create_time
        - deviceToken
        - email
        - email_is_null
        - email_status
        - employee_number
        - extras
        - first_name
        - full_name
        - groups
        - id
        - isMember
        - isOwner
        - isSuperAdmin
        - last_name
        - local_account_exist
        - login_time
        - maskedEmail
        - nfc_card_status
        - nfc_card_type
        - nfc_display_id
        - nfc_token
        - only_local_account
        - password_revision
        - permissionMask
        - permissions
        - phone
        - role
        - roleId
        - roles
        - scopes
        - ssoAuth
        - sso_account
        - sso_picture
        - sso_username
        - sso_uuid
        - status
        - uid_account_status
        - uid_sso_account
        - uid_sso_id
        - unique_id
        - update_time
        - user_email
        - username
    Extras:
      title: Extras
      description: Extra things on the user
      type: object
      additionalProperties: false
    Group:
      title: Group
      description: What groups the user is in
      type: object
      additionalProperties: false
      properties:
        unique_id:
          type: string
        name:
          type: string
        up_id:
          type: string
        up_ids:
          type: array
          items: {}
        system_name:
          type: string
        create_time:
          type: string
      required:
        - create_time
        - name
        - system_name
        - unique_id
        - up_id
        - up_ids
    Permissions:
      title: Permissions
      description: Permissions that the user has
      type: object
      additionalProperties: false
      properties:
        network.management:
          type: array
          items:
            type: string
        protect.management:
          type: array
          items:
            type: string
        system.management.location:
          type: array
          items:
            type: string
        system.management.user:
          type: array
          items:
            type: string
      required:
        - network.management
        - protect.management
        - system.management.location
        - system.management.user
    Role:
      title: Role
      description: User roles
      type: object
      additionalProperties: false
      properties:
        unique_id:
          type: string
        name:
          type: string
        system_role:
          type: boolean
        system_key:
          type: string
        level:
          type: integer
        create_time:
          type: string
        update_time:
          type: string
        is_private:
          type: boolean
      required:
        - create_time
        - is_private
        - level
        - name
        - system_key
        - system_role
        - unique_id
        - update_time
